### PR TITLE
Derive Generic for the UTF8 wrapper type

### PR DESCRIPTION
**Pull request by ddssff**

### CODE REVIEW

**Comment by ddssff** [comment]
It would be good to know whether this pull will eventually be merged or whether I should look for a different workaround.

**Comment by glguy** [comment]
This type is intended to be abstract and generally shouldn't have it's representation exposed (e.g. via Generics). What's the usecase for a Generic instance here?

**Comment by ddssff** [comment]
I'm generalizing the text type used by the pretty package from String to a type class.  It needs the superclass NFData from deepseq, which needs the superclass Generic.

https://github.com/haskell/pretty/blob/master/src/Text/PrettyPrint/Annotated/HughesPJ.hs#L301

https://github.com/haskell/deepseq/blob/master/Control/DeepSeq.hs#L270

It looks like I might be able to make an NFData instance without a Generic instance.  I was just going by what the compiler told me before.

**Comment by glguy** [comment]
NFData only requires a Generic instance to automatically derive the definition of rnf. You can define

```haskell
utf8rnf :: NFData a => UTF8 a -> ()
utf8rnf = rnf . toRep
```

locally without creating an orphan instance or using Generics

**Comment by ddssff** [comment]
Thanks!

**Pull request closed without merging**
